- name: Create a file
  hosts: all
  tasks:

 ## Update all packages inside apt module
 
    - name: update
      apt:
        name: "*"
        state:  present

## Install nginx latest version

    - name: Install Nginx
      apt:
        name: nginx
        state: latest

## Update the module apt 

    - name: Update apt cache
      become: yes
      apt:
        update_cache: yes

## Install software properties for PHP installation

    - name: Install software-properties-common
      become: yes
      apt:
        name: software-properties-common
        state: present

## Ensure apt_repository module is used to add PPA to the system 

    - name: Add PPA for ondrej/php
      become: yes
      apt_repository:
        repo: "ppa:ondrej/php"

## Update apt module

    - name: Update apt cache after adding PPA
      become: yes
      apt:
        update_cache: yes

## Install PHP7.3

    - name: Install PHP 7.3
      become: yes
      apt:
        name: php7.3
        state: present

## Install PHP required packages

    - name: Install required packages
      apt:
        name:
          - php7.3-fpm
          - php7.3-cli
          - php7.3-curl
          - php7.3-mbstring
          - php7.3-mysql
        state: present

## Download composer.phar on /tmp/composer

    - name: Download composer installer
      uri:
        url: https://getcomposer.org/installer
        dest: /tmp/composer

## Install composer in directory /usr/local/bin

    - name: install composer
      shell: php /tmp/composer --install-dir=/usr/local/bin
      become: yes

## Rename composer packages 

    - name: rename composer executable
      shell: mv /usr/local/bin/composer.phar /usr/local/bin/composer
      become: yes

## set permission for composer file '0775'

    - name: set permissions for composer file
      file:
        path: /usr/local/bin/composer
        mode: a+x
        state: file
      become: yes

## clone laravel and create project laravelapp

    - name: clone laravel codebase
      git:
        repo: https://github.com/laravel/laravel.git
        dest: /var/www/html/laravelapp
      become: yes

## Ensure permission for laravel stroage folder

    - name: set permission for laravel storage folder
      file:
        path: /var/www/html/laravelapp
        state: directory
        mode: '0775'
      become: yes

## copy the .env file from master to control node

    - name: copy file .env
      copy:
        src: /etc/ansible/.env
        dest: /var/www/html/BZBoss/.env

## Remove the file default from a path /etc/nginx/sites-enabled/default

    - name: Remove file default in nginx path
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

## Copy the file default from master to control node

    - name: copy the default file
      copy:
        src: /etc/ansible/default
        dest: /etc/nginx/sites-available/default

## Use symbolic line module to link a file default 

    - name: symbolic link a file Default
      ansible.builtin.shell: ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

## Restart nginx 

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
     
## Generate php artisan key:generate

    - name: Run php artisan key generate
      command: php artisan key:generate
      args:
        chdir: /var/www/html/BZBoss

## Link the storage to php artisan

    - name: Link storage to PHP artisan
      command: php artisan storage:link
      args:
        chdir: /var/www/html/BZBoss

## Ensure ownership to storage link        

    - name: Ownership to storage:link
      command: sudo chmod o+w ./storage/ -R
      args:
        chdir: /var/www/html/BZBoss

